(()=>{'use strict';
const $=s=>document.querySelector(s),C=(v,a,b)=>Math.max(a,Math.min(b,v)),T=Math.PI*2;
const S=[
 ['lighter','01','LIGHTER','ライター','TAP / HOLD','光った写真を燃やす',112,31,'#ffad58','255,173,88','some things are better left as ash.','tap'],
 ['match','02','MATCH','マッチ','SWIPE →','右へ擦って火をつける',124,31,'#ef7446','239,116,70','one strike. one chance.','swipe'],
 ['camera','03','CAMERA','カメラ','TAP','一瞬の光を切り取る',132,31,'#9bc7ff','155,199,255','keep what disappears fastest.','tap'],
 ['soda','04','SODA','炭酸缶','FLICK ↑','上へ弾いてプルタブを開ける',140,31,'#7ee9dc','126,233,220','a little pressure makes it sparkle.','flick'],
 ['typewriter','05','TYPEWRITER','タイプライター','TAP','文字をリズムで打ち込む',152,33,'#ead7ad','234,215,173','leave a line worth remembering.','tap']
].map(x=>({id:x[0],no:x[1],name:x[2],jp:x[3],gesture:x[4],hint:x[5],bpm:x[6],dur:x[7],accent:x[8],rgb:x[9],story:x[10],input:x[11]}));
const R={grid:$('#stageGrid'),game:$('#game'),cv:$('#world'),g:$('#world').getContext('2d'),title:$('#hudTitle'),no:$('#hudNo'),sub:$('#hudSub'),combo:$('#combo'),score:$('#score'),bar:$('#progressBar'),dot:$('#progressDot'),judge:$('#judgement'),gesture:$('#gesture'),story:$('#story'),count:$('#countdown'),flash:$('#flash'),heat:$('#heatWash'),input:$('#inputSurface')};
const Q={ctx:null,master:null,i:0,playing:false,start:0,raf:0,notes:[],score:0,combo:0,max:0,p:0,g:0,o:0,m:0,pointer:null,hold:null,particles:[],echo:[],typed:'',shake:0,pulse:0};
function show(id){document.querySelectorAll('.screen').forEach(e=>e.classList.remove('active'));$(id).classList.add('active')}
function key(i){return'beatRitualV2_'+S[i].id}
function obj(id){return`<div class="object-preview"><div class="obj-${id==='typewriter'?'type':id}"></div></div>`}
function home(){R.grid.innerHTML=S.map((s,i)=>`<button class="stage-card" data-i="${i}" style="--card:${s.accent}"><span class="no">STAGE ${s.no}</span><div class="object">${obj(s.id)}</div><h2>${s.name}</h2><span class="jp">${s.jp} — ${s.gesture}</span><div class="tag"><span>${s.bpm} BPM</span><span class="best">BEST ${(+localStorage.getItem(key(i))||0).toLocaleString()}</span></div></button>`).join('');R.grid.querySelectorAll('button').forEach(b=>b.onclick=()=>run(+b.dataset.i))}
function audio(){if(Q.ctx){Q.ctx.resume?.();return}const A=window.AudioContext||window.webkitAudioContext;Q.ctx=new A;Q.master=Q.ctx.createGain();Q.master.gain.value=.7;Q.master.connect(Q.ctx.destination)}
function tone(t,f,d=.06,type='sine',v=.06,to=f){const o=Q.ctx.createOscillator(),g=Q.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(Math.max(30,to),t+d);g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(Q.master);o.start(t);o.stop(t+d+.02)}
function noise(t,d=.08,v=.04,hp=1400){let n=Math.ceil(Q.ctx.sampleRate*d),b=Q.ctx.createBuffer(1,n,Q.ctx.sampleRate),a=b.getChannelData(0);for(let i=0;i<n;i++)a[i]=Math.random()*2-1;let s=Q.ctx.createBufferSource(),f=Q.ctx.createBiquadFilter(),g=Q.ctx.createGain();s.buffer=b;f.type='highpass';f.frequency.value=hp;g.gain.setValueAtTime(v,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);s.connect(f);f.connect(g);g.connect(Q.master);s.start(t)}
function sfx(id){let t=Q.ctx.currentTime;if(id==='lighter'){tone(t,1600,.025,'square',.06,700);tone(t+.02,520,.08,'triangle',.08,180);noise(t+.03,.13,.04,1700)}if(id==='match'){noise(t,.07,.09,900);tone(t+.04,400,.12,'triangle',.07,160)}if(id==='camera'){tone(t,1000,.02,'square',.07,450);noise(t+.012,.03,.06,2300)}if(id==='soda'){tone(t,660,.03,'square',.06,220);noise(t+.02,.23,.06,2500)}if(id==='typewriter'){tone(t,1150,.025,'square',.055,500);tone(t+.014,310,.04,'triangle',.03,170)}}
function music(s){let b=60/s.bpm;for(let t=0;t<s.dur;t+=b){let n=Math.round(t/b),at=Q.start+t;if(n%4===0)tone(at,110,.1,'sine',.11,45);if(n%4===2)noise(at,.07,.035,1000);noise(at+b*.5,.025,.018,5000);if(n%2===0)tone(at,[165,196,220,247][(n/2)%4|0],b*.65,'sine',.013)}}
function pattern(s){let b=60/s.bpm,a=[],id=0;for(let bar=1;bar*4*b<s.dur-1;bar++){let p=bar<2?[0,1,2,3]:bar%3?[0,.5,1.5,2,3]:[0,.5,1,1.5,2.5,3,3.5];for(let k of p){let t=bar*4*b+k*b;if(t<s.dur-.6)a.push({id:id++,t,hit:0,miss:0,hold:s.id==='lighter'&&id%12===8,holding:0,seed:Math.random()*99,letter:'RHYTHMMAKESHABIT'[id%16]})}}return a}
function reset(){Object.assign(Q,{score:0,combo:0,max:0,p:0,g:0,o:0,m:0,pointer:null,hold:null,particles:[],echo:[],typed:'',shake:0,pulse:0});R.combo.textContent='0';R.score.textContent='000000';R.bar.style.width=R.dot.style.left='0'}
async function run(i){audio();cancelAnimationFrame(Q.raf);Q.playing=false;Q.i=i;let s=S[i];reset();Q.notes=pattern(s);document.documentElement.style.setProperty('--accent',s.accent);document.documentElement.style.setProperty('--accent-rgb',s.rgb);R.title.textContent=s.name;R.no.textContent='STAGE '+s.no;R.sub.textContent=s.id==='lighter'?'BURN THE FLASH':s.id==='match'?'SCRATCH THE BEAT':s.id==='camera'?'CATCH THE LIGHT':s.id==='soda'?'CRACK THE FIZZ':'WRITE THE RHYTHM';R.gesture.innerHTML=`<b>${s.gesture}</b><span>${s.hint}</span>`;R.story.textContent=s.story;show('#game');resize();await countdown();Q.start=Q.ctx.currentTime+.22;music(s);Q.playing=true;Q.raf=requestAnimationFrame(loop)}
function countdown(){return new Promise(ok=>{let a=['3','2','1','GO'],i=0;R.count.style.display='flex';let f=()=>{if(i===a.length){R.count.style.display='none';ok();return}R.count.innerHTML=`<div class="count-pop">${a[i++]}</div>`;setTimeout(f,570)};f()})}
function loop(){if(!Q.playing)return;let s=S[Q.i],now=Q.ctx.currentTime-Q.start;for(let n of Q.notes)if(!n.hit&&!n.miss&&!n.holding&&now-n.t>.24){n.miss=1;Q.m++;Q.combo=0;R.combo.textContent=0}fx();draw(now,s);let p=C(now/s.dur,0,1);R.bar.style.width=R.dot.style.left=p*100+'%';if(now>=s.dur)return finish();Q.raf=requestAnimationFrame(loop)}
function nearest(now){let z=null,d=9;for(let n of Q.notes){if(n.hit||n.miss)continue;let x=Math.abs(now-n.t);if(x<d){z=n;d=x}if(n.t>now+.35)break}return[z,d]}
function judge(n,d){let a=d<=.075?['PERFECT',1000,'#fff0ba','p']:d<=.135?['GREAT',720,'#bde5ff','g']:['GOOD',430,'#bce8c9','o'];n.hit=1;Q[a[3]]++;Q.combo++;Q.max=Math.max(Q.max,Q.combo);Q.score+=Math.round(a[1]*(1+Math.min(1.4,Math.floor(Q.combo/10)*.2)));R.combo.textContent=Q.combo;R.score.textContent=String(Q.score).padStart(6,'0');pop(a[0],a[2]);sfx(S[Q.i].id);impact(n);navigator.vibrate?.(a[0]==='PERFECT'?12:7)}
function miss(){Q.combo=0;R.combo.textContent=0;pop('MISS','#ff6d7d');Q.shake=5}
function pop(t,c){R.judge.textContent=t;R.judge.style.color=c;R.judge.classList.remove('show');void R.judge.offsetWidth;R.judge.classList.add('show')}
function impact(n){let s=S[Q.i];Q.pulse=1;Q.shake=2.4;R.heat.classList.remove('on');void R.heat.offsetWidth;R.heat.classList.add('on');if(s.id==='camera'){R.flash.classList.remove('on');void R.flash.offsetWidth;R.flash.classList.add('on')}if(s.id==='lighter')Q.echo.push({seed:n.seed,born:performance.now()});if(s.id==='typewriter')Q.typed=(Q.typed+n.letter).slice(-20);for(let i=0;i<20;i++)Q.particles.push({x:.285,y:.57,vx:(Math.random()-.5)*.16,vy:-.05-Math.random()*.14,l:1,r:1+Math.random()*2})}
function tap(now){let[n,d]=nearest(now);if(!n||d>.24)return miss();if(n.hold){n.holding=1;n.hs=performance.now();n.hd=d;Q.hold=n;return}judge(n,d)}
function fx(){Q.pulse*=.9;Q.shake*=.82;for(let p of Q.particles){p.x+=p.vx*.016;p.y+=p.vy*.016;p.vy+=.0008;p.l-=.025}Q.particles=Q.particles.filter(p=>p.l>0);Q.echo=Q.echo.filter(e=>performance.now()-e.born<850)}
function resize(){let d=Math.min(devicePixelRatio||1,2),r=R.cv.getBoundingClientRect();R.cv.width=r.width*d;R.cv.height=r.height*d;R.g.setTransform(d,0,0,d,0,0)}
function rr(g,x,y,w,h,r){g.beginPath();g.roundRect?g.roundRect(x,y,w,h,r):(g.rect(x,y,w,h));g.closePath()}
function bg(g,w,h,s){let x=g.createLinearGradient(0,0,w,h),a=s.id==='lighter'?['#161719','#080b10']:s.id==='match'?['#28160e','#08090b']:s.id==='camera'?['#071827','#100d13']:s.id==='soda'?['#0a2b2c','#071014']:['#2b251c','#090909'];x.addColorStop(0,a[0]);x.addColorStop(1,a[1]);g.fillStyle=x;g.fillRect(0,0,w,h);let q=g.createRadialGradient(w*.29,h*.6,0,w*.29,h*.6,w*.45);q.addColorStop(0,`rgba(${s.rgb},${.06+.08*Q.pulse})`);q.addColorStop(1,'transparent');g.fillStyle=q;g.fillRect(0,0,w,h)}
function X(n,now,w){if(n.holding)return w*.285;let hit=w*.285,spawn=w*1.1,p=1-(n.t-now)/2.55;return hit+(spawn-hit)*(1-p)}
function guide(g,x,y){g.strokeStyle='rgba(255,255,255,.17)';g.setLineDash([3,8]);g.beginPath();g.moveTo(x,y-75);g.lineTo(x,y+95);g.stroke();g.setLineDash([])}
function lighter(g,w,h,now,s){let y=h*.29,hit=w*.285;g.strokeStyle='rgba(110,80,55,.7)';g.lineWidth=3;g.beginPath();g.moveTo(0,y);g.quadraticCurveTo(w*.5,y+12,w,y);g.stroke();for(let n of Q.notes){if(n.hit||n.miss)continue;let x=X(n,now,w);if(x<-120||x>w+120)continue;let ph=h*.26,pw=ph*.76,d=Math.abs(n.t-now);g.save();g.translate(x,y+10);g.rotate(Math.sin(n.seed)*.035);g.shadowColor=s.accent;g.shadowBlur=d<.24?25:0;g.fillStyle='#ded6c8';rr(g,-pw/2,0,pw,ph,3);g.fill();g.shadowBlur=0;g.fillStyle=`hsl(${n.seed*37%360} 20% 28%)`;g.fillRect(-pw/2+8,8,pw-16,ph*.67);g.fillStyle='rgba(245,230,205,.65)';g.font=`italic ${Math.max(9,ph*.07)}px Georgia`;g.textAlign='center';g.fillText(n.hold?'keep burning':'still here.',0,ph*.86);if(d<.24){g.fillStyle='rgba(255,255,255,.2)';g.fillRect(-pw/2+8,8,pw-16,ph*.67)}g.restore()}for(let e of Q.echo){let a=1-(performance.now()-e.born)/850,ph=h*.26,pw=ph*.76,r=(1-a)*ph*.55;g.save();g.globalAlpha=a;g.translate(hit,y+10);g.rotate(Math.sin(e.seed)*.035);g.fillStyle='#b9aa95';rr(g,-pw/2,0,pw,ph,3);g.fill();g.fillStyle='#281914';g.beginPath();g.arc(pw*.25,ph*.7,r,0,T);g.fill();g.strokeStyle=s.accent;g.lineWidth=3;g.shadowBlur=15;g.shadowColor=s.accent;g.beginPath();g.arc(pw*.25,ph*.7,r,2.1,4.7);g.stroke();g.restore()}guide(g,hit,y+80);g.save();g.translate(hit,h*.79);let l=g.createLinearGradient(-45,-70,45,150);l.addColorStop(0,'#ef9b4b');l.addColorStop(.5,'#a54719');l.addColorStop(1,'#4b1d0c');g.fillStyle=l;rr(g,-44,-25,88,175,14);g.fill();let m=g.createLinearGradient(-44,0,44,0);m.addColorStop(0,'#4a4a4c');m.addColorStop(.5,'#c7c0b5');m.addColorStop(1,'#303136');g.fillStyle=m;rr(g,-43,-76,86,60,8);g.fill();let f=g.createLinearGradient(0,-165,0,-72);f.addColorStop(0,'transparent');f.addColorStop(.2,'#fff6bd');f.addColorStop(.6,'#ff9b32');f.addColorStop(.9,'#5b77ff');g.fillStyle=f;g.shadowBlur=25;g.shadowColor='#ff8a35';g.beginPath();g.moveTo(-8,-72);g.bezierCurveTo(-28,-110,-8,-150,0,-160);g.bezierCurveTo(28,-115,18,-92,8,-72);g.fill();g.restore()}
function match(g,w,h,now,s){let y=h*.53,hit=w*.27;for(let i=0;i<10;i++){g.strokeStyle='rgba(121,68,37,.11)';g.beginPath();g.moveTo(0,h*.18+i*h*.07);g.lineTo(w,h*.15+i*h*.07);g.stroke()}g.fillStyle='rgba(84,38,22,.65)';g.fillRect(hit-17,y-86,34,172);for(let n of Q.notes){if(n.hit||n.miss)continue;let x=X(n,now,w),d=Math.abs(n.t-now);if(x<-110||x>w+110)continue;g.strokeStyle='#d2a76e';g.lineWidth=7;g.beginPath();g.moveTo(x-75,y);g.lineTo(x+20,y);g.stroke();g.fillStyle=d<.24?s.accent:'#762a22';g.shadowBlur=d<.24?18:0;g.shadowColor=s.accent;g.beginPath();g.arc(x+27,y,11,0,T);g.fill();g.shadowBlur=0}guide(g,hit,y)}
function camera(g,w,h,now,s){let hit=w*.31,hy=h*.62;for(let i=0;i<17;i++){let bw=35+(i%4)*16,bh=50+(i%6)*22,x=(i*91+performance.now()/350)%(w+80)-40;g.fillStyle='rgba(7,14,24,.8)';g.fillRect(x,hy-bh,bw,bh);g.fillStyle='rgba(255,210,140,.12)';for(let yy=hy-bh+12;yy<hy-8;yy+=16)g.fillRect(x+9,yy,4,6)}for(let n of Q.notes){if(n.hit||n.miss)continue;let x=X(n,now,w),d=Math.abs(n.t-now);if(x<-90||x>w+90)continue;g.strokeStyle=d<.24?'#fff':'rgba(220,235,255,.35)';g.lineWidth=d<.24?2:1;g.strokeRect(x-52,h*.38,104,72)}g.save();g.translate(hit,h*.79);g.fillStyle='#111319';rr(g,-120,-50,240,100,18);g.fill();g.fillStyle='#050609';g.beginPath();g.arc(25,0,52,0,T);g.fill();let l=g.createRadialGradient(25,0,1,25,0,44);l.addColorStop(0,'#9bd4ef');l.addColorStop(.25,'#224d63');l.addColorStop(1,'#090b0e');g.fillStyle=l;g.beginPath();g.arc(25,0,43,0,T);g.fill();g.restore();guide(g,hit,h*.44)}
function soda(g,w,h,now,s){let hit=w*.27,y=h*.53;for(let i=0;i<25;i++){g.strokeStyle='rgba(180,255,245,.08)';g.beginPath();g.arc((i*73+performance.now()/300)%(w+40),i*53%h,2+i%5,0,T);g.stroke()}for(let n of Q.notes){if(n.hit||n.miss)continue;let x=X(n,now,w),d=Math.abs(n.t-now);if(x<-70||x>w+70)continue;let q=g.createLinearGradient(x-25,0,x+25,0);q.addColorStop(0,'#497f7c');q.addColorStop(.3,'#d5efec');q.addColorStop(.55,d<.24?s.accent:'#71aaa6');q.addColorStop(1,'#376562');g.fillStyle=q;rr(g,x-25,y-59,50,118,10);g.fill();g.fillStyle='#174845';g.font='bold 13px sans-serif';g.textAlign='center';g.fillText('FIZZ',x,y+5)}g.fillStyle='rgba(5,19,20,.6)';rr(g,hit-95,h*.76,190,48,17);g.fill();g.fillStyle='rgba(200,255,248,.4)';g.font='11px sans-serif';g.fillText('↑ FLICK TO CRACK',hit,h*.79);guide(g,hit,y)}
function typewriter(g,w,h,now,s){let hit=w*.27,pw=Math.min(w*.5,520),ph=h*.43;g.fillStyle='#e5d9c1';g.fillRect(hit,h*.2,pw,ph);g.fillStyle='rgba(55,48,42,.2)';for(let y=h*.25;y<h*.58;y+=25)g.fillRect(hit+25,y,pw-50,1);g.fillStyle='#3b352f';g.font='20px Georgia';g.fillText(Q.typed||'_',hit+30,h*.27);for(let n of Q.notes){if(n.hit||n.miss)continue;let x=X(n,now,w),d=Math.abs(n.t-now);if(x<-50||x>w+50)continue;g.fillStyle=d<.24?'#f4e6c6':'rgba(235,217,180,.5)';g.font='bold 24px Georgia';g.fillText(n.letter,x,h*.56)}g.save();g.translate(hit,h*.82);g.fillStyle='#2b2926';rr(g,-180,-58,360,116,20);g.fill();for(let r=0;r<3;r++)for(let c=0;c<10;c++){g.fillStyle=(r+c)%5?'#151515':'#62594d';rr(g,-145+c*31+(r%2)*8,-28+r*29,23,19,4);g.fill()}g.restore();guide(g,hit,h*.52)}
function particles(g,w,h,s){for(let p of Q.particles){g.globalAlpha=p.l;g.fillStyle=s.accent;g.shadowBlur=7;g.shadowColor=s.accent;g.beginPath();g.arc(p.x*w,p.y*h,p.r,0,T);g.fill()}g.globalAlpha=1;g.shadowBlur=0}
function draw(now,s){let g=R.g,w=R.cv.clientWidth,h=R.cv.clientHeight;g.clearRect(0,0,w,h);g.save();g.translate((Math.random()-.5)*Q.shake,(Math.random()-.5)*Q.shake);bg(g,w,h,s);({lighter,match,camera,soda,typewriter}[s.id])(g,w,h,now,s);particles(g,w,h,s);g.restore()}
function finish(){Q.playing=false;cancelAnimationFrame(Q.raf);let total=Q.notes.length,a=total?(Q.p+Q.g*.75+Q.o*.4)/total:0,rank=a>=.93?'S':a>=.82?'A':a>=.68?'B':a>=.5?'C':'D',old=+localStorage.getItem(key(Q.i))||0;if(Q.score>old)localStorage.setItem(key(Q.i),Q.score);let s=S[Q.i];$('#resultStage').textContent=`STAGE ${s.no} / ${s.name}`;$('#rank').textContent=rank;$('#finalScore').textContent=Q.score.toLocaleString();$('#stPerfect').textContent=Q.p;$('#stGreat').textContent=Q.g;$('#stGood').textContent=Q.o;$('#stMiss').textContent=Q.m;$('#bestText').textContent=(Q.score>old?'NEW BEST ✦  ':'BEST '+old.toLocaleString()+'  /  ')+`MAX COMBO ${Q.max}`;$('#nextBtn').style.display=Q.i<S.length-1?'block':'none';show('#results');home()}
R.input.onpointerdown=e=>{if(!Q.playing)return;e.preventDefault();Q.pointer={x:e.clientX,y:e.clientY,t:performance.now()};let s=S[Q.i],now=Q.ctx.currentTime-Q.start;if(s.input==='tap')tap(now)};
R.input.onpointerup=e=>{if(!Q.playing||!Q.pointer)return;let p=Q.pointer;Q.pointer=null;let s=S[Q.i],now=Q.ctx.currentTime-Q.start;if(Q.hold){let n=Q.hold;Q.hold=null;n.holding=0;if(performance.now()-n.hs>=360)judge(n,n.hd);else{n.miss=1;Q.m++;miss()}return}let[n,d]=nearest(now),dx=e.clientX-p.x,dy=e.clientY-p.y,dt=performance.now()-p.t;if(!n||d>.24)return miss();if(s.input==='swipe'&&dx>42&&Math.abs(dx)>Math.abs(dy)*1.2&&dt<700)judge(n,d);else if(s.input==='flick'&&dy<-36&&Math.abs(dy)>Math.abs(dx)&&dt<600)judge(n,d);else if(s.input!=='tap')miss()};
document.onkeydown=e=>{if(Q.playing&&(e.code==='Space'||e.code==='Enter')){e.preventDefault();tap(Q.ctx.currentTime-Q.start)}};window.onresize=resize;$('#backBtn').onclick=()=>{Q.playing=false;cancelAnimationFrame(Q.raf);show('#home');home()};$('#homeBtn').onclick=()=>{show('#home');home()};$('#retryBtn').onclick=()=>run(Q.i);$('#nextBtn').onclick=()=>Q.i<S.length-1&&run(Q.i+1);$('#allBtn').onclick=()=>run(0);$('#howBtn').onclick=()=>$('#howDialog').showModal();$('#howClose').onclick=()=>$('#howDialog').close();document.addEventListener('dblclick',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});home();
})();
