(() => {
'use strict';
const $=s=>document.querySelector(s);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const stages=[
 {id:'lighter',no:'01',name:'LIGHTER',jp:'ライター',sub:'CLICK / IGNITE',icon:'🔥',bpm:112,dur:24,accent:'#ffb24a',accent2:'#ff6845',bg:'radial-gradient(circle at 74% 38%,rgba(255,150,54,.22),transparent 21%),linear-gradient(130deg,#26170d,#0b0c12 56%,#17100c)',desc:'カチッ、シュボッ。火が点く瞬間をビートに。',sfx:'lighter'},
 {id:'match',no:'02',name:'MATCH',jp:'マッチ',sub:'SCRATCH / FLARE',icon:'🕯️',bpm:124,dur:25,accent:'#f39a55',accent2:'#e55335',bg:'radial-gradient(circle at 62% 30%,rgba(252,126,64,.22),transparent 19%),linear-gradient(145deg,#32160f,#120f12 50%,#08090e)',desc:'シュッ…ボッ。擦れる音と着火の余韻。',sfx:'match'},
 {id:'camera',no:'03',name:'CAMERA',jp:'カメラ',sub:'FOCUS / SHUTTER',icon:'📷',bpm:132,dur:25,accent:'#84b5ff',accent2:'#d9ecff',bg:'radial-gradient(circle at 75% 28%,rgba(116,174,255,.20),transparent 22%),linear-gradient(135deg,#0e2237,#0c0d12 55%,#151922)',desc:'カシャッ。街の光を一拍ずつ切り取る。',sfx:'camera'},
 {id:'soda',no:'04',name:'SODA',jp:'炭酸缶',sub:'CRACK / FIZZ',icon:'🥤',bpm:140,dur:25,accent:'#74e4d3',accent2:'#d8fff8',bg:'radial-gradient(circle at 66% 28%,rgba(97,236,211,.18),transparent 22%),linear-gradient(140deg,#0b2b2b,#0b1015 56%,#0c1720)',desc:'カシュッ、プシュ〜。弾ける炭酸で加速。',sfx:'soda'},
 {id:'typewriter',no:'05',name:'TYPEWRITER',jp:'タイプライター',sub:'CLACK / DING',icon:'⌨️',bpm:152,dur:27,accent:'#f2dfb9',accent2:'#ffffff',bg:'radial-gradient(circle at 72% 31%,rgba(238,221,184,.13),transparent 24%),linear-gradient(145deg,#29241b,#101114 56%,#171511)',desc:'カタ、カタ、チーン。最後は音が文章になる。',sfx:'typewriter'}
];
const state={stageIndex:0,all:false,queue:[],ctx:null,master:null,startTime:0,raf:0,notes:[],nextNote:0,playing:false,score:0,combo:0,maxCombo:0,perfect:0,great:0,good:0,miss:0,hitCount:0,lastInput:0,stageStartWall:0};
const refs={home:$('#home'),game:$('#game'),results:$('#results'),grid:$('#stageGrid'),canvas:$('#canvas'),ctx2d:$('#canvas').getContext('2d'),bg:$('#gameBg'),item:$('#item'),title:$('#hudTitle'),sub:$('#hudSub'),combo:$('#combo'),score:$('#score'),judgement:$('#judgement'),progress:$('#progressBar'),fever:$('#fever'),countdown:$('#countdown')};
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function bestKey(i){return 'beatRitualBest_'+stages[i].id}
function buildHome(){refs.grid.innerHTML=stages.map((s,i)=>`<button class="stage-card" data-stage="${i}" style="--card-accent:${s.accent}"><span class="num">STAGE ${s.no}</span><span class="icon">${s.icon}</span><h2>${s.name}</h2><p>${s.desc}</p><div class="meta"><span>${s.bpm} BPM</span><span>BEST ${(+localStorage.getItem(bestKey(i))||0).toLocaleString()}</span></div></button>`).join(''); refs.grid.querySelectorAll('.stage-card').forEach(b=>b.addEventListener('click',()=>startSelected(+b.dataset.stage,false)))}
function ensureAudio(){if(state.ctx&&state.ctx.state!=='closed'){if(state.ctx.state==='suspended')state.ctx.resume();return} const AC=window.AudioContext||window.webkitAudioContext;state.ctx=new AC();state.master=state.ctx.createGain();state.master.gain.value=.78;state.master.connect(state.ctx.destination)}
function noiseBuffer(seconds=.15){const n=Math.floor(state.ctx.sampleRate*seconds),b=state.ctx.createBuffer(1,n,state.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=Math.random()*2-1;return b}
function tone(t,f=220,d=.06,type='sine',gain=.12,f2=null){const o=state.ctx.createOscillator(),g=state.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(f2)o.frequency.exponentialRampToValueAtTime(Math.max(20,f2),t+d);g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g);g.connect(state.master);o.start(t);o.stop(t+d+.02)}
function burst(t,d=.06,gain=.08,high=1000){const src=state.ctx.createBufferSource(),g=state.ctx.createGain(),f=state.ctx.createBiquadFilter();src.buffer=noiseBuffer(d);f.type='highpass';f.frequency.value=high;g.gain.setValueAtTime(gain,t);g.gain.exponentialRampToValueAtTime(.0001,t+d);src.connect(f);f.connect(g);g.connect(state.master);src.start(t);src.stop(t+d+.02)}
function kick(t){tone(t,115,.11,'sine',.16,48)} function hat(t){burst(t,.025,.035,5000)} function snare(t){burst(t,.08,.065,1200);tone(t,175,.055,'triangle',.04,100)}
function stageSfx(kind,t=state.ctx.currentTime){switch(kind){case'lighter': tone(t,1800,.025,'square',.075,900);tone(t+.025,620,.055,'triangle',.07,240);burst(t+.035,.12,.04,1800);break;case'match':burst(t,.085,.095,900);tone(t+.055,410,.12,'triangle',.07,180);burst(t+.07,.16,.045,1300);break;case'camera':tone(t,980,.018,'square',.08,520);burst(t+.016,.028,.08,1800);tone(t+.052,760,.02,'square',.065,360);break;case'soda':tone(t,600,.025,'square',.07,250);burst(t+.02,.22,.07,2200);break;case'typewriter':tone(t,1250,.025,'square',.06,620);tone(t+.014,340,.035,'triangle',.04,180);break;}}
function scheduleBacking(stage){const beat=60/stage.bpm, start=state.startTime;for(let t=0;t<stage.dur+1;t+=beat){const at=start+t;const b=Math.round(t/beat);if(b%4===0)kick(at);if(b%4===2)snare(at);if(b%1===0)hat(at+.5*beat);if(stage.id==='typewriter'&&b%8===7){tone(at+.72*beat,1320,.28,'sine',.055,1040)}}}
function makePattern(stage){const beat=60/stage.bpm, arr=[];let k=0;for(let bar=1;bar*4*beat<stage.dur-1.2;bar++){const base=bar*4*beat;let pat;if(bar<2)pat=[0,1,2,3];else if(bar<4)pat=[0,.5,1.5,2,3];else if(bar%3===0)pat=[0,.5,1,1.5,2.5,3,3.5];else pat=[0,1,1.5,2,2.5,3.5];for(const p of pat){const time=base+p*beat;if(time<stage.dur-.65)arr.push({time,id:k++,hit:false,missed:false,accent:(k%8===0),pulse:(k%4===0)})}}return arr}
function resetStats(){Object.assign(state,{score:0,combo:0,maxCombo:0,perfect:0,great:0,good:0,miss:0,hitCount:0,nextNote:0});refs.combo.textContent='0';refs.score.textContent='000000';refs.progress.style.width='0';refs.fever.classList.remove('on')}
function startSelected(index,all){ensureAudio();state.stageIndex=index;state.all=all;state.queue=all?stages.map((_,i)=>i).slice(index):[index];runStage(index)}
async function runStage(index){cancelAnimationFrame(state.raf);state.playing=false;state.stageIndex=index;const s=stages[index];resetStats();state.notes=makePattern(s);refs.bg.style.background=s.bg;refs.item.textContent=s.icon;refs.title.textContent=s.name;refs.sub.textContent=s.sub;document.documentElement.style.setProperty('--accent',s.accent);show('#game');resize();await countdown();ensureAudio();state.startTime=state.ctx.currentTime+.28;state.stageStartWall=performance.now();scheduleBacking(s);state.playing=true;state.raf=requestAnimationFrame(loop)}
function countdown(){return new Promise(resolve=>{let seq=['3','2','1','GO'];let i=0;refs.countdown.style.display='flex';const next=()=>{if(i>=seq.length){refs.countdown.style.display='none';resolve();return}refs.countdown.innerHTML=`<div class="count-pop">${seq[i++]}</div>`;setTimeout(next,620)};next()})}
function loop(){if(!state.playing)return;const s=stages[state.stageIndex],now=state.ctx.currentTime-state.startTime;refs.progress.style.width=`${clamp(now/s.dur*100,0,100)}%`;autoMiss(now);draw(now,s);if(now>=s.dur){finishStage();return}state.raf=requestAnimationFrame(loop)}
function autoMiss(now){for(const n of state.notes){if(n.hit||n.missed)continue;if(now-n.time>.24){n.missed=true;state.miss++;state.combo=0;refs.combo.textContent='0';refs.fever.classList.remove('on')}}}
function input(){if(!state.playing)return;const wall=performance.now();if(wall-state.lastInput<32)return;state.lastInput=wall;const now=state.ctx.currentTime-state.startTime;let target=null,best=Infinity;for(const n of state.notes){if(n.hit||n.missed)continue;const d=Math.abs(now-n.time);if(d<best){best=d;target=n}if(n.time>now+.28)break}if(!target||best>.24){flashJudge('MISS', '#ff667d');state.combo=0;refs.combo.textContent='0';return}target.hit=true;state.hitCount++;const s=stages[state.stageIndex];let label,pts,color;if(best<=.085){label='PERFECT';pts=1000;color='#fff7c8';state.perfect++}else if(best<=.145){label='GREAT';pts=700;color='#b8efff';state.great++}else{label='GOOD';pts=400;color='#aee7c4';state.good++}state.combo++;state.maxCombo=Math.max(state.maxCombo,state.combo);const mult=1+Math.min(1.5,Math.floor(state.combo/10)*.25);state.score+=Math.round(pts*mult);refs.combo.textContent=state.combo;refs.score.textContent=String(state.score).padStart(6,'0');flashJudge(label,color);stageSfx(s.sfx);refs.item.classList.remove('hit');void refs.item.offsetWidth;refs.item.classList.add('hit');if(state.combo>=10)refs.fever.classList.add('on');navigator.vibrate?.(label==='PERFECT'?12:7)}
function flashJudge(text,color){refs.judgement.textContent=text;refs.judgement.style.color=color;refs.judgement.classList.remove('show');void refs.judgement.offsetWidth;refs.judgement.classList.add('show')}
function resize(){const dpr=Math.min(window.devicePixelRatio||1,2),r=refs.canvas.getBoundingClientRect();refs.canvas.width=Math.round(r.width*dpr);refs.canvas.height=Math.round(r.height*dpr);refs.ctx2d.setTransform(dpr,0,0,dpr,0,0)}
function draw(now,s){const c=refs.ctx2d,w=refs.canvas.clientWidth,h=refs.canvas.clientHeight;c.clearRect(0,0,w,h);const laneY=h*.56,hitX=w*.215,spawnX=w*1.06,travel=2.25;
 c.save();c.strokeStyle='rgba(255,255,255,.12)';c.lineWidth=2;c.beginPath();c.moveTo(0,laneY);c.lineTo(w,laneY);c.stroke();c.strokeStyle='rgba(255,255,255,.82)';c.lineWidth=3;c.beginPath();c.moveTo(hitX,laneY-72);c.lineTo(hitX,laneY+72);c.stroke();c.shadowBlur=20;c.shadowColor=s.accent;c.strokeStyle=s.accent;c.lineWidth=2;c.beginPath();c.arc(hitX,laneY,30,0,Math.PI*2);c.stroke();c.restore();
 for(const n of state.notes){if(n.hit||n.missed)continue;const dt=n.time-now;if(dt>travel+.2||dt<-.3)continue;const p=1-dt/travel,x=hitX+(spawnX-hitX)*(1-p),r=n.accent?18:14;c.save();c.globalAlpha=clamp((travel-dt)*2,0,1);c.shadowBlur=n.accent?24:12;c.shadowColor=s.accent;c.strokeStyle=n.accent?'#fff':s.accent;c.lineWidth=n.accent?5:3;c.beginPath();c.arc(x,laneY,r,0,Math.PI*2);c.stroke();if(n.pulse){c.globalAlpha*=.35;c.beginPath();c.arc(x,laneY,r+10,0,Math.PI*2);c.stroke()}c.restore()}
 const t=performance.now()/1000;c.save();for(let i=0;i<18;i++){const x=(w-((t*(16+i%4)*20+i*113)% (w+80)))+40,y=(i*83%h),a=.018+(i%3)*.008;c.fillStyle=`rgba(255,255,255,${a})`;c.beginPath();c.arc(x,y,1+(i%2),0,Math.PI*2);c.fill()}c.restore()}
function finishStage(){state.playing=false;cancelAnimationFrame(state.raf);const total=state.notes.length,acc=total?((state.perfect+state.great*.75+state.good*.4)/total):0;let rank=acc>=.93?'S':acc>=.82?'A':acc>=.68?'B':acc>=.5?'C':'D';const old=+localStorage.getItem(bestKey(state.stageIndex))||0,isBest=state.score>old;if(isBest)localStorage.setItem(bestKey(state.stageIndex),state.score);$('#rank').textContent=rank;$('#finalScore').textContent=state.score.toLocaleString();$('#stPerfect').textContent=state.perfect;$('#stGreat').textContent=state.great;$('#stGood').textContent=state.good;$('#stMiss').textContent=state.miss;$('#bestText').textContent=isBest?'NEW BEST ✦ 前回の記録を更新しました':`BEST ${old.toLocaleString()}  /  MAX COMBO ${state.maxCombo}`;const nextIndex=state.stageIndex+1;const unlock=$('#unlockText');if(nextIndex<stages.length&&isBest){unlock.style.display='block';unlock.textContent=`NEXT SOUND → ${stages[nextIndex].jp}「${stages[nextIndex].name}」`}else unlock.style.display='none';$('#nextBtn').style.display=nextIndex<stages.length?'block':'none';show('#results');buildHome()}
function abort(){state.playing=false;cancelAnimationFrame(state.raf);show('#home');buildHome()}
window.addEventListener('resize',resize);document.addEventListener('pointerdown',e=>{if(refs.game.classList.contains('active')&&state.playing&&!e.target.closest('button'))input()},{passive:true});document.addEventListener('keydown',e=>{if((e.code==='Space'||e.code==='Enter')&&state.playing){e.preventDefault();input()}});
$('#backBtn').onclick=abort;$('#homeBtn').onclick=()=>{show('#home');buildHome()};$('#retryBtn').onclick=()=>runStage(state.stageIndex);$('#nextBtn').onclick=()=>{const ni=state.stageIndex+1;if(ni<stages.length)runStage(ni);else{show('#home');buildHome()}};$('#allBtn').onclick=()=>startSelected(0,true);$('#howBtn').onclick=()=>alert('右から流れてくるリングが白いラインに重なった瞬間、画面のどこかをタップ。\n\nPC：Space / Enterでも操作できます。\nPERFECTを10回つなぐとFEVER。ステージごとに音とテンポが変化します。');
buildHome();
})();
