(()=>{
'use strict';
const PREF='deckDive_audio_v1';
let prefs=(()=>{try{return Object.assign({bgm:true,se:true,vibration:true,bgmVol:.34,seVol:.58},JSON.parse(localStorage.getItem(PREF)||'{}'))}catch{return{bgm:true,se:true,vibration:true,bgmVol:.34,seVol:.58}}})();
const A={ctx:null,bgmGain:null,seGain:null,track:'menu',timer:null,step:0,unlocked:false};
function ctx(){if(A.ctx)return A.ctx;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;A.ctx=new AC();A.bgmGain=A.ctx.createGain();A.seGain=A.ctx.createGain();A.bgmGain.connect(A.ctx.destination);A.seGain.connect(A.ctx.destination);levels();return A.ctx}
function levels(){if(A.bgmGain)A.bgmGain.gain.value=prefs.bgm?prefs.bgmVol:0;if(A.seGain)A.seGain.gain.value=prefs.se?prefs.seVol:0;if(A.unlocked){if(prefs.bgm)startClock();else stopClock()}}
function save(){localStorage.setItem(PREF,JSON.stringify(prefs));levels()}
function unlock(){const c=ctx();if(!c)return;c.resume?.();A.unlocked=true;levels()}
document.addEventListener('pointerdown',unlock,{once:true,passive:true});
function tone(f,d=.12,g=.03,type='triangle',bus='se',delay=0){const c=ctx();if(!c||!f)return;const o=c.createOscillator(),v=c.createGain(),out=bus==='bgm'?A.bgmGain:A.seGain,t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(f,t);v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(Math.max(.0002,g),t+.01);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(out);o.start(t);o.stop(t+d+.03)}
function noise(d=.09,g=.08,cut=1800,delay=0){const c=ctx();if(!c)return;const n=Math.max(1,Math.floor(c.sampleRate*d)),buf=c.createBuffer(1,n,c.sampleRate),arr=buf.getChannelData(0);for(let i=0;i<n;i++)arr[i]=(Math.random()*2-1)*(1-i/n);const s=c.createBufferSource(),f=c.createBiquadFilter(),v=c.createGain(),t=c.currentTime+delay;s.buffer=buf;f.type='bandpass';f.frequency.setValueAtTime(cut,t);f.frequency.exponentialRampToValueAtTime(Math.max(280,cut*.34),t+d);f.Q.value=.7;v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);s.connect(f);f.connect(v);v.connect(A.seGain);s.start(t)}
function buzz(kind='tap'){if(!prefs.vibration||!navigator.vibrate)return;const m={tap:7,slash:11,block:12,magic:8,boss:[28,30,50],hit:16};navigator.vibrate(m[kind]||7)}
function sound(kind){if(!prefs.se){buzz(kind);return}unlock();if(kind==='slash'){noise(.11,.12,2600);tone(185,.08,.05,'sawtooth');buzz('slash')}else if(kind==='heavy'){noise(.15,.14,1500);tone(92,.13,.07,'square');buzz('hit')}else if(kind==='block'){tone(520,.07,.05,'square');tone(760,.1,.025,'triangle','se',.025);buzz('block')}else if(kind==='magic'){tone(520,.12,.026,'sine');tone(780,.18,.02,'sine','se',.04);buzz('magic')}else if(kind==='boss'){tone(58,.4,.06,'sawtooth');tone(42,.45,.04,'square','se',.05);buzz('boss')}else if(kind==='relic'){tone(760,.16,.026,'sine');tone(1140,.24,.018,'sine','se',.08)}else{tone(260,.045,.025,'triangle');buzz('tap')}}
const seq={menu:[220,null,277,null,330,null,277,null],map:[165,null,null,220,null,196,null,null,247,null,null,220,null,null,null,null],battle:[110,165,110,196,123,185,123,220],boss:[73,73,110,82,73,123,65,110],event:[146,null,null,220,null,null,174,null,null,261,null,null],shop:[196,null,247,null,294,null,247,null],rest:[220,null,null,277,null,null,330,null,null,277,null,null],reward:[262,null,330,null,392,null,494,null],result:[262,330,392,523,392,330,262,null]};
function tick(){if(!prefs.bgm||!A.unlocked)return;const q=seq[A.track]||seq.map,n=q[A.step++%q.length];if(!n)return;const fast=A.track==='battle'||A.track==='boss';tone(n,fast?.13:.28,fast?.02:.014,A.track==='boss'?'sawtooth':'triangle','bgm');if(fast&&A.step%4===1)tone(n*.5,.18,.011,'square','bgm')}
function startClock(){if(A.timer)return;A.timer=setInterval(tick,A.track==='battle'?190:A.track==='boss'?220:340)}
function stopClock(){if(A.timer){clearInterval(A.timer);A.timer=null}}
function track(t){if(A.track===t)return;A.track=t;A.step=0;stopClock();if(A.unlocked&&prefs.bgm)startClock()}
function detectTrack(){const s=document.getElementById('screen');if(!s)return'menu';const cl=s.className,html=s.innerHTML;if(cl.includes('boss-battle'))return'boss';if(cl.includes('battle-screen'))return'battle';if(cl.includes('event-world'))return'event';if(cl.includes('result-world'))return'result';if(/class="[^"]*shop-screen/.test(html))return'shop';if(/class="[^"]*rest-screen/.test(html))return'rest';if(/class="[^"]*reward-screen/.test(html))return'reward';if(cl.includes('map-act-'))return'map';return'menu'}
function diverSvg(){const name=(document.getElementById('hudCharName')?.textContent||'BREAKER').trim();const col={BREAKER:'#6fe7ff',ALCHEMIST:'#83ffae',TRICKSTER:'#ffd166',SENTINEL:'#86a8ff',ORACLE:'#c49cff'}[name]||'#6fe7ff';return `<svg class="dd-mini-diver" viewBox="0 0 32 32" aria-hidden="true"><circle cx="16" cy="7" r="5" fill="${col}"/><rect x="11" y="12" width="10" height="11" rx="3" fill="${col}"/><rect x="7" y="13" width="5" height="4" rx="2" fill="${col}"/><rect x="20" y="13" width="5" height="4" rx="2" fill="${col}"/><rect x="11" y="22" width="4" height="8" rx="2" fill="${col}"/><rect x="17" y="22" width="4" height="8" rx="2" fill="${col}"/><rect x="13" y="5" width="2" height="2" fill="#08111d"/><rect x="18" y="5" width="2" height="2" fill="#08111d"/></svg>`}
function polishMap(){document.querySelectorAll('.route-diver').forEach(el=>{if(!el.querySelector('.dd-mini-diver'))el.innerHTML=diverSvg()});const lg=document.querySelector('.route-legend');if(lg&&!lg.dataset.dd){lg.dataset.dd='1';lg.innerHTML=lg.textContent.replace(/現在地.*/,'現在地 ')+`<span class="dd-now-label">${diverSvg()}</span>`}}
function polishIntents(){document.querySelectorAll('.intent').forEach(el=>{if(el.dataset.dd)return;const t=el.textContent.trim();el.dataset.dd='1';let type='special',sub='特殊行動';if(t.startsWith('⚔️')){type='attack';sub=t.includes('×')?'連続攻撃':'攻撃'}else if(t.startsWith('🛡️')&&t.includes('⚔️')){type='mixed';sub='防御＋攻撃'}else if(t.startsWith('🛡️')){type='block';sub='防御'}else if(t.startsWith('🔥 +')){type='buff';sub='強化'}else if(/☠️|💔|🌀/.test(t)){type='debuff';sub='弱体'}else if(t==='DOWN'){type='special';sub='撃破'}el.classList.add('dd-intent-'+type);el.innerHTML=`<span class="dd-intent-main">${t}</span><span class="dd-intent-sub">${sub}</span>`})}
function settings(){const modal=document.getElementById('modal'),box=document.getElementById('modalContent');if(!modal||!box)return;box.innerHTML=`<div class="act-badge">SYSTEM</div><h2>サウンド設定</h2><div class="dd-settings-panel"><div class="dd-toggle"><span><b>🎵 BGM</b><small>探索・戦闘・ボスで切替</small></span><button class="dd-pill ${prefs.bgm?'on':''}" data-t="bgm">${prefs.bgm?'ON':'OFF'}</button></div><div class="dd-volume"><b>BGM音量</b><input type="range" min="0" max="100" value="${Math.round(prefs.bgmVol*100)}" data-r="bgmVol"><output>${Math.round(prefs.bgmVol*100)}</output></div><div class="dd-toggle"><span><b>⚔️ 効果音</b><small>斬撃・盾・魔法・レリック</small></span><button class="dd-pill ${prefs.se?'on':''}" data-t="se">${prefs.se?'ON':'OFF'}</button></div><div class="dd-volume"><b>SE音量</b><input type="range" min="0" max="100" value="${Math.round(prefs.seVol*100)}" data-r="seVol"><output>${Math.round(prefs.seVol*100)}</output></div><div class="dd-toggle"><span><b>📳 振動</b><small>ヒット・ボス・操作感</small></span><button class="dd-pill ${prefs.vibration?'on':''}" data-t="vibration">${prefs.vibration?'ON':'OFF'}</button></div><button class="secondary" id="ddSlashTest">⚔️ 斬撃音をテスト</button></div>`;modal.classList.remove('hidden');box.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>{prefs[b.dataset.t]=!prefs[b.dataset.t];save();settings()});box.querySelectorAll('[data-r]').forEach(r=>r.oninput=()=>{prefs[r.dataset.r]=Number(r.value)/100;r.nextElementSibling.value=r.value;save()});document.getElementById('ddSlashTest').onclick=()=>sound('slash')}
function ensureSettingsButton(){const row=document.querySelector('.hud-mainrow');if(row&&!document.getElementById('ddSettings')){const b=document.createElement('button');b.id='ddSettings';b.className='icon-btn dd-settings-btn';b.textContent='⚙';b.setAttribute('aria-label','設定');b.onclick=settings;row.appendChild(b)}const menu=document.querySelector('.menu-stack');if(menu&&!document.getElementById('ddHomeSettings')){const b=document.createElement('button');b.id='ddHomeSettings';b.className='secondary';b.textContent='SETTINGS';b.onclick=settings;menu.appendChild(b)}}
function cardSoundFrom(el){const type=el.querySelector('.card-type')?.textContent||'',name=el.querySelector('.card-name')?.textContent||'';if(type.includes('ATTACK'))sound(/ヘビー|オーバー|エクスキューション|アイアン/.test(name)?'heavy':'slash');else if(/ガード|ウォール|パリィ|シールド|反射|要塞/.test(name))sound('block');else sound('magic')}
document.addEventListener('pointerup',e=>{const card=e.target.closest?.('.card[data-play-card]');if(card)cardSoundFrom(card);const relic=e.target.closest?.('.relic-icon');if(relic)sound('relic')},true);
const mo=new MutationObserver(()=>{ensureSettingsButton();polishMap();polishIntents();track(detectTrack())});mo.observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});ensureSettingsButton();polishMap();polishIntents();track(detectTrack());
})();