const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const {URL}=require('url');const PORT=process.env.PORT||3000,ROOT=path.join(__dirname,'public'),rooms=new Map(),MATCH_MS=60000;
const J=(r,s,d)=>{const b=JSON.stringify(d);r.writeHead(s,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});r.end(b)};
const body=q=>new Promise((ok,ng)=>{let b='';q.on('data',c=>{b+=c;if(b.length>20000)q.destroy()});q.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch(e){ng(e)}});q.on('error',ng)});
const tok=()=>crypto.randomBytes(12).toString('hex');function code(){for(let i=0;i<200;i++){const c=String(1000+Math.floor(Math.random()*9000));if(!rooms.has(c))return c}throw Error('room full')}
const name=(v,f)=>(String(v||'').trim().replace(/[<>]/g,'').slice(0,12)||f),get=c=>rooms.get(String(c||'')),idx=(r,t)=>r.players.findIndex(p=>p&&p.token===t);
const state=r=>({players:r.players.map(p=>p?{name:p.name,connected:p.connected,score:p.score}:null),started:r.started,counting:r.counting,hostCanStart:!!(r.players[0]?.connected&&r.players[1]?.connected&&!r.started&&!r.counting)});
function send(p,m){for(const s of p.streams)try{s.write(`data: ${JSON.stringify(m)}\n\n`)}catch{}}function all(r,m){r.players.forEach(p=>p&&send(p,m))}const lobby=r=>all(r,{type:'lobby',state:state(r)});
function sh(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function clearRound(r){clearInterval(r.mv);clearTimeout(r.nx);r.mv=r.nx=null}function clearMatch(r){clearRound(r);clearTimeout(r.matchTimer);(r.phaseTimers||[]).forEach(clearTimeout);r.phaseTimers=[];clearInterval(r.cd);r.matchTimer=r.cd=null}
function phaseForElapsed(ms){if(ms<15000)return{phase:1,cols:3,count:9,pool:18,move:0,swaps:0};if(ms<30000)return{phase:2,cols:4,count:16,pool:26,move:0,swaps:0};if(ms<45000)return{phase:3,cols:5,count:25,pool:34,move:1900,swaps:1};return{phase:4,cols:6,count:36,pool:40,move:1500,swaps:2}}
function makeOrder(count,pool){return sh(Array.from({length:pool},(_,i)=>i)).slice(0,count)}
function startCountdown(r){if(r.started||r.counting||!r.players[0]?.connected||!r.players[1]?.connected)return;r.counting=true;let n=3;all(r,{type:'countdown',value:n});r.cd=setInterval(()=>{n--;if(n>0)return all(r,{type:'countdown',value:n});clearInterval(r.cd);r.cd=null;r.counting=false;startMatch(r)},1000);lobby(r)}
function startMatch(r){clearMatch(r);r.started=true;r.sudden=false;r.startedAt=Date.now();r.endAt=r.startedAt+MATCH_MS;r.players.forEach(p=>{p.score=0;p.lock=0});all(r,{type:'game_start',endAt:r.endAt,durationMs:MATCH_MS,scores:[0,0]});startRound(r);r.phaseTimers=[15000,30000,45000].map(ms=>setTimeout(()=>{if(!r.started||r.sudden)return;all(r,{type:'phase_change'});startRound(r,true)},ms));r.matchTimer=setTimeout(()=>finishTime(r),MATCH_MS)}
function startRound(r){if(!r.started)return;clearRound(r);const elapsed=r.sudden?45000:Math.max(0,Date.now()-r.startedAt);const d=r.sudden?{phase:5,cols:5,count:25,pool:34,move:0,swaps:0}:phaseForElapsed(elapsed);const order=makeOrder(d.count,d.pool),target=order[Math.floor(Math.random()*order.length)],id=(r.round?.id||0)+1;r.round={id,target,order,res:false,d};all(r,{type:'round',roundId:id,target,order,cols:d.cols,phase:d.phase,moveMs:d.move,sudden:r.sudden});if(d.move)r.mv=setInterval(()=>{if(!r.started||!r.round||r.round.res)return;const o=[...r.round.order];for(let s=0;s<d.swaps;s++){const a=Math.floor(Math.random()*o.length);let b=Math.floor(Math.random()*o.length);if(a===b)b=(b+1)%o.length;[o[a],o[b]]=[o[b],o[a]]}r.round.order=o;all(r,{type:'move',roundId:id,order:o})},d.move)}
function resolveRound(r,w){if(!r.round||r.round.res)return;r.round.res=true;clearInterval(r.mv);r.mv=null;if(r.sudden)return endMatch(r,w,'sudden');r.players[w].score++;const scores=r.players.map(p=>p.score);all(r,{type:'round_winner',winnerIndex:w,scores});if(Date.now()>=r.endAt)return;r.nx=setTimeout(()=>startRound(r),520)}
function finishTime(r){if(!r.started)return;clearRound(r);const s=r.players.map(p=>p.score);if(s[0]!==s[1])return endMatch(r,s[0]>s[1]?0:1,'time');r.sudden=true;all(r,{type:'sudden_death',scores:s});setTimeout(()=>startRound(r),700)}
function endMatch(r,w,reason){if(!r.started)return;clearMatch(r);r.started=false;r.counting=false;r.sudden=false;const scores=r.players.map(p=>p.score);all(r,{type:'match_end',winnerIndex:w,scores,reason});lobby(r)}
function serve(res,u){let p=u==='/'?'/index.html':u;const f=path.normalize(path.join(ROOT,p));if(!f.startsWith(ROOT))return J(res,403,{error:'forbidden'});fs.readFile(f,(e,d)=>{if(e)return J(res,404,{error:'not found'});let ct='application/octet-stream';if(p.endsWith('.html'))ct='text/html; charset=utf-8';else if(p.endsWith('.css'))ct='text/css; charset=utf-8';else if(p.endsWith('.js'))ct='text/javascript; charset=utf-8';res.writeHead(200,{'content-type':ct,'cache-control':'no-cache'});res.end(d)})}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'x'}`);
if(req.method==='GET'&&u.pathname==='/health')return J(res,200,{ok:true,rooms:rooms.size});
if(req.method==='GET'&&u.pathname==='/events'){const r=get(u.searchParams.get('room')),t=u.searchParams.get('token')||'';if(!r)return J(res,404,{error:'room not found'});const i=idx(r,t);if(i<0)return J(res,403,{error:'bad token'});const p=r.players[i];res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache, no-transform','connection':'keep-alive','x-accel-buffering':'no'});res.write(': ok\n\n');p.connected=true;p.streams.add(res);send(p,{type:'lobby',state:state(r)});lobby(r);const ka=setInterval(()=>{try{res.write(': keepalive\n\n')}catch{}},15000);req.on('close',()=>{clearInterval(ka);p.streams.delete(res);if(!p.streams.size){p.connected=false;if(r.started){r.started=false;clearMatch(r);all(r,{type:'room_closed'})}lobby(r)}});return}
if(req.method==='POST'&&u.pathname.startsWith('/api/')){let b;try{b=await body(req)}catch{return J(res,400,{error:'invalid json'})}
if(u.pathname==='/api/create'){const c=code(),p={token:tok(),name:name(b.name,'PLAYER 1'),connected:false,score:0,lock:0,streams:new Set()};rooms.set(c,{code:c,players:[p,null],started:false,counting:false,round:null,phaseTimers:[]});return J(res,200,{room:c,token:p.token,playerIndex:0})}
if(u.pathname==='/api/join'){const r=get(b.room);if(!r)return J(res,404,{error:'その部屋は見つかりません'});if(r.started||r.counting)return J(res,409,{error:'ゲーム開始中です'});if(r.players[1])return J(res,409,{error:'その部屋は満員です'});const p={token:tok(),name:name(b.name,'PLAYER 2'),connected:false,score:0,lock:0,streams:new Set()};r.players[1]=p;lobby(r);return J(res,200,{room:r.code,token:p.token,playerIndex:1})}
const r=get(b.room);if(!r)return J(res,404,{error:'部屋がありません'});const i=idx(r,b.token);if(i<0)return J(res,403,{error:'認証エラー'});const p=r.players[i];
if(u.pathname==='/api/start'){if(i!==0)return J(res,403,{error:'ホストだけが開始できます'});if(!r.players[1]?.connected)return J(res,409,{error:'相手の参加を待っています'});startCountdown(r);return J(res,200,{ok:true})}
if(u.pathname==='/api/guess'){if(!r.started||!r.round||r.round.res)return J(res,200,{accepted:false,reason:'closed'});if(+b.roundId!==r.round.id)return J(res,200,{accepted:false,reason:'old'});const now=Date.now();if(now<p.lock)return J(res,200,{accepted:false,reason:'locked'});if(+b.charId===r.round.target){resolveRound(r,i);return J(res,200,{accepted:true,correct:true})}p.lock=now+850;send(p,{type:'wrong'});return J(res,200,{accepted:true,correct:false})}
if(u.pathname==='/api/leave'){p.connected=false;p.streams.forEach(s=>{try{s.end()}catch{}});p.streams.clear();if(i===0){all(r,{type:'room_closed'});clearMatch(r);rooms.delete(r.code)}else{r.players[1]=null;r.started=false;clearMatch(r);lobby(r)}return J(res,200,{ok:true})}
return J(res,404,{error:'unknown api'})}
if(req.method==='GET')return serve(res,u.pathname);J(res,405,{error:'method'})}).listen(PORT,'0.0.0.0',()=>console.log('WANTED '+PORT));
