const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path');
const {URL}=require('url');const PORT=process.env.PORT||3000,ROOT=path.join(__dirname,'public'),rooms=new Map();
const J=(r,s,d)=>{const b=JSON.stringify(d);r.writeHead(s,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});r.end(b)};
const body=q=>new Promise((ok,ng)=>{let b='';q.on('data',c=>b+=c);q.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch(e){ng(e)}});q.on('error',ng)});
const tok=()=>crypto.randomBytes(12).toString('hex');
function code(){for(let i=0;i<200;i++){const c=String(1000+Math.floor(Math.random()*9000));if(!rooms.has(c))return c}throw Error('room full')}
const name=(v,f)=>(String(v||'').trim().replace(/[<>]/g,'').slice(0,12)||f);
const idx=(r,t)=>r.players.findIndex(p=>p&&p.token===t);const get=c=>rooms.get(String(c||''));
function state(r){return{players:r.players.map(p=>p?{name:p.name,ready:p.ready,connected:p.connected,score:p.score}:null),started:r.started}}
function send(p,m){for(const s of p.streams)try{s.write(`data: ${JSON.stringify(m)}\n\n`)}catch{}}
function all(r,m){r.players.forEach(p=>p&&send(p,m))}const lobby=r=>all(r,{type:'lobby',state:state(r)});
function sh(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const lv=n=>Math.min(20,n+1);function dif(l){if(l<=5)return[3,9,18,0,0];if(l<=10)return[4,16,26,0,0];if(l<=15)return[5,25,34,1900,1];return[6,36,40,1500,2]}
function clear(r){clearInterval(r.mv);clearTimeout(r.nx);clearInterval(r.cd);r.mv=r.nx=r.cd=null}
function countdown(r){if(r.started||r.counting||!r.players[0]||!r.players[1]||!r.players.every(p=>p.connected&&p.ready))return;r.counting=true;let n=3;all(r,{type:'countdown',value:n});r.cd=setInterval(()=>{n--;if(n>0)return all(r,{type:'countdown',value:n});clearInterval(r.cd);r.counting=false;startMatch(r)},1000)}
function startMatch(r){clear(r);r.started=true;r.roundNo=0;r.players.forEach(p=>{p.score=0;p.ready=false;p.lock=0});all(r,{type:'game_start'});r.nx=setTimeout(()=>round(r),450)}
function round(r){if(!r.started)return;clearInterval(r.mv);const l=lv(r.roundNo),[cols,count,pool,move,swaps]=dif(l),order=sh(Array.from({length:pool},(_,i)=>i)).slice(0,count),target=order[Math.floor(Math.random()*order.length)],id=(r.round?.id||0)+1;r.round={id,target,order,res:false};all(r,{type:'round',roundId:id,roundNumber:r.roundNo,level:l,target,order,cols,moveMs:move});if(move)r.mv=setInterval(()=>{if(!r.started||r.round.res)return;const o=[...r.round.order];for(let s=0;s<swaps;s++){const a=Math.floor(Math.random()*o.length);let b=Math.floor(Math.random()*o.length);if(a===b)b=(b+1)%o.length;[o[a],o[b]]=[o[b],o[a]]}r.round.order=o;all(r,{type:'move',roundId:id,order:o})},move)}
function winRound(r,w){if(r.round.res)return;r.round.res=true;clearInterval(r.mv);r.players[w].score++;const scores=r.players.map(p=>p.score);all(r,{type:'round_winner',winnerIndex:w,scores});if(scores[w]>=10){r.started=false;return r.nx=setTimeout(()=>{all(r,{type:'match_end',winnerIndex:w,scores});lobby(r)},650)}r.roundNo++;r.nx=setTimeout(()=>round(r),700)}
function serve(res,u){let p=u==='/'?'/index.html':u;const f=path.normalize(path.join(ROOT,p));if(!f.startsWith(ROOT))return J(res,403,{error:'forbidden'});fs.readFile(f,(e,d)=>{if(e)return J(res,404,{error:'not found'});res.writeHead(200,{'content-type':p.endsWith('.html')?'text/html; charset=utf-8':'application/octet-stream','cache-control':'no-cache'});res.end(d)})}
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'x'}`);
if(req.method==='GET'&&u.pathname==='/health')return J(res,200,{ok:true,rooms:rooms.size});
if(req.method==='GET'&&u.pathname==='/events'){const r=get(u.searchParams.get('room')),t=u.searchParams.get('token')||'';if(!r)return J(res,404,{error:'room not found'});const i=idx(r,t);if(i<0)return J(res,403,{error:'bad token'});const p=r.players[i];res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache, no-transform','connection':'keep-alive','x-accel-buffering':'no'});res.write(': ok\n\n');p.connected=true;p.streams.add(res);send(p,{type:'lobby',state:state(r)});lobby(r);const ka=setInterval(()=>{try{res.write(': keepalive\n\n')}catch{}},15000);req.on('close',()=>{clearInterval(ka);p.streams.delete(res);if(!p.streams.size){p.connected=false;p.ready=false;lobby(r)}});return}
if(req.method==='POST'&&u.pathname.startsWith('/api/')){let b;try{b=await body(req)}catch{return J(res,400,{error:'invalid json'})}
if(u.pathname==='/api/create'){const c=code(),p={token:tok(),name:name(b.name,'PLAYER 1'),ready:false,connected:false,score:0,lock:0,streams:new Set()};rooms.set(c,{code:c,players:[p,null],started:false,counting:false,roundNo:0,round:null});return J(res,200,{room:c,token:p.token,playerIndex:0})}
if(u.pathname==='/api/join'){const r=get(b.room);if(!r)return J(res,404,{error:'その部屋は見つかりません'});if(r.started)return J(res,409,{error:'ゲーム中です'});if(r.players[1])return J(res,409,{error:'その部屋は満員です'});const p={token:tok(),name:name(b.name,'PLAYER 2'),ready:false,connected:false,score:0,lock:0,streams:new Set()};r.players[1]=p;lobby(r);return J(res,200,{room:r.code,token:p.token,playerIndex:1})}
const r=get(b.room);if(!r)return J(res,404,{error:'部屋がありません'});const i=idx(r,b.token);if(i<0)return J(res,403,{error:'認証エラー'});const p=r.players[i];
if(u.pathname==='/api/ready'){if(r.started||r.counting)return J(res,409,{error:'開始処理中です'});p.ready=!!b.ready;lobby(r);countdown(r);return J(res,200,{ok:true})}
if(u.pathname==='/api/reset'){clear(r);r.started=r.counting=false;r.players.forEach(x=>{if(x){x.score=0;x.ready=false;x.lock=0}});lobby(r);return J(res,200,{ok:true})}
if(u.pathname==='/api/guess'){if(!r.started||!r.round||r.round.res)return J(res,200,{accepted:false,reason:'closed'});if(+b.roundId!==r.round.id)return J(res,200,{accepted:false,reason:'old'});const now=Date.now();if(now<p.lock)return J(res,200,{accepted:false,reason:'locked'});if(+b.charId===r.round.target){winRound(r,i);return J(res,200,{accepted:true,correct:true})}p.lock=now+850;send(p,{type:'wrong'});return J(res,200,{accepted:true,correct:false})}
if(u.pathname==='/api/leave'){p.ready=false;p.connected=false;p.streams.forEach(s=>{try{s.end()}catch{}});p.streams.clear();if(i===0){all(r,{type:'room_closed'});clear(r);rooms.delete(r.code)}else{r.players[1]=null;r.started=false;clear(r);lobby(r)}return J(res,200,{ok:true})}
return J(res,404,{error:'unknown api'})}
if(req.method==='GET')return serve(res,u.pathname);J(res,405,{error:'method'})}).listen(PORT,'0.0.0.0',()=>console.log('WANTED '+PORT));
